const actionTypes = {
	// Auth Types
	REGISTER_SUCCESS: "REGISTER_SUCCESS",
	REGISTER_FAILED: "REGISTER_FAILED",
	SIGNIN_SUCCESS: "SIGNIN_SUCCESS",
	SIGNIN_FAILED: "SIGNIN_FAILED",
	LOGOUT: "LOGOUT",
	SEND_FORGOT_PWD_EMAIL: "SEND_FORGOT_PWD_EMAIL",
	CHECK_TOKEN: "CHECK_TOKEN",

	// Book Types
	GET_ALL_BOOKS: "GET_ALL_BOOKS",
	GET_ONE_BOOK: "GET_ONE_BOOK",
	SET_BOOK: "SET_BOOK",
	CREATE_BOOK: "CREATE_BOOK",
	UPDATE_BOOK: "UPDATE_BOOK",
	DELETE_BOOK: "DELETE_BOOK",
	CLEAR_BOOK: "CLEAR_BOOK",
	BUY_BOOK: "BUY_BOOK",
	REFUND_BOOK: "REFUND_BOOK",
	CHANGE_USER_BALANCE:"CHANGE_USER_BALANCE",

	// Loading
	LOAD: "LOAD",
	STOP_LOAD: "STOP_LOAD",
	
}

export default actionTypes;