const actionTypes = {
	// Auth Types
	REGISTER_SUCCESS: "REGISTER_SUCCESS",
	REGISTER_FAILED: "REGISTER_FAILED",
	SIGNIN_SUCCESS: "SIGNIN_SUCCESS",
	SIGNIN_FAILED: "SIGNIN_FAILED",
	SEND_FORGOT_PWD_EMAIL: "SEND_FORGOT_PWD_EMAIL",
	CHECK_TOKEN: "CHECK_TOKEN",

	// Book Types
	GET_ALL_BOOKS: "GET_ALL_BOOKS",
	GET_ONE_BOOK: "GET_ONE_BOOK",
	CREATE_BOOK: "CREATE_BOOK",
	UPDATE_BOOK: "UPDATE_BOOK",
	DELETE_BOOK: "DELETE_BOOK",
	CLEAR_BOOK: "CLEAR_BOOK",
}

export default actionTypes;