const actionTypes = {
	REGISTER_SUCCESS: "REGISTER_SUCCESS",
	REGISTER_FAILED: "REGISTER_FAILED",
	SIGNIN_SUCCESS: "SIGNIN_SUCCESS",
	SIGNIN_FAILED: "SIGNIN_FAILED",
	SEND_FORGOT_PWD_EMAIL: "SEND_FORGOT_PWD_EMAIL",
	
}

export default actionTypes;